/**
 * 画像の出典一覧。
 *
 * ■ このページの役割
 *   ライセンスが要求する作者表示は、画像のすぐ近くに出すのが原則です。
 *   このページは**その代わり**ではなく、まとめて確認するための補助です
 *   （各画像のクレジットは WikimediaImage が画像と同じ figure に描画します）。
 *
 * ■ 掲載していない画像は、このページにも出しません
 *   「一覧に出ている ＝ 掲載可否の確認が済んでいる」という関係を保つためです。
 */
import type { Metadata } from "next";
import Link from "next/link";

import { findLocale, localeCodes } from "@/sports/i18n";
import { resolveLocale } from "@/sports/lib/page";
import { sportsMetadata } from "@/sports/lib/seo";
import { href } from "@/sports/lib/url";
import { Breadcrumbs, JsonLd, SectionHeading } from "@/sports/components/ui/primitives";
import { breadcrumbJsonLd } from "@/sports/lib/structured-data";

import { ImageLicenseBadge } from "@/media/components";
import { wikimediaAssets, getLocalization } from "@/media/data/assets";
import { getPagesUsingAsset } from "@/media/data/usages";
import { thirdPartyAssets } from "@/media/data/third-party";
import { getMediaLabels } from "@/media/i18n/labels";
import { isPublishable } from "@/media/lib/eligibility";
import { getLicense } from "@/media/lib/license";

export function generateStaticParams() {
  return localeCodes.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const info = findLocale(locale);
  if (!info) return {};
  const labels = getMediaLabels(info.code);
  return sportsMetadata({
    locale: info.code,
    path: "/image-credits",
    title: labels.creditsTitle,
    description: labels.creditsIntro,
  });
}

export default async function ImageCreditsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale, dict } = await resolveLocale(params);
  const labels = getMediaLabels(locale);
  const ja = locale === "ja";

  // 掲載できる状態の画像だけを並べます
  const published = wikimediaAssets
    .filter(isPublishable)
    .sort((a, b) => a.fileName.localeCompare(b.fileName));

  const trail = [
    { label: "HOME", path: "/" },
    { label: labels.creditsTitle, path: "/image-credits" },
  ];

  return (
    <>
      <Breadcrumbs locale={locale} trail={trail} />

      <header className="mb-10">
        <p className="sp-eyebrow mb-2">IMAGE CREDITS</p>
        <h1 className="text-ink text-3xl font-extrabold sm:text-4xl">{labels.creditsTitle}</h1>
        <p className="text-ink-dim mt-3 max-w-3xl text-sm leading-relaxed">{labels.creditsIntro}</p>
      </header>

      {/* 自前で作った素材と、第三者素材を分けて示します */}
      <section aria-labelledby="ic-own" className="mb-12">
        <SectionHeading
          id="ic-own"
          eyebrow="OWN WORK"
          title={ja ? "当サイトが作成した素材" : "Created by this site"}
        />
        <div className="sp-solid text-ink-soft p-5 text-sm leading-relaxed">
          {ja ? (
            <>
              <p>
                チームエンブレム・選手のシルエット・カードの背景・OGP画像は、すべて当サイトが
                プログラムで生成したものです。第三者の著作物は含まれていません。
              </p>
              <p className="mt-2">
                チームロゴ・リーグロゴ・選手写真は、権利処理が済むまで掲載していません（
                <Link href={href(locale, "/legal/copyright")} className="text-cyan hover:underline">
                  著作権・画像利用方針
                </Link>
                ）。
              </p>
            </>
          ) : (
            <>
              <p>
                Team crests, player silhouettes, card backgrounds and OG images are generated by
                this site in code. They contain no third-party work.
              </p>
              <p className="mt-2">
                Club and league logos and player photographs are not published until the rights are
                cleared.
              </p>
            </>
          )}
        </div>
      </section>

      {thirdPartyAssets.length > 0 ? (
        <section aria-labelledby="ic-third" className="mb-12">
          <SectionHeading
            id="ic-third"
            eyebrow="THIRD PARTY"
            title={ja ? "第三者素材" : "Third-party assets"}
            description={
              ja
                ? "Wikimedia Commons 以外の、ライセンスに基づいて利用している素材です。"
                : "Assets used under licence from sources other than Wikimedia Commons."
            }
          />
          <ul className="space-y-3">
            {thirdPartyAssets.map((asset) => (
              <li key={asset.id} className="sp-solid p-4">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  {/* 素材名とライセンス名は識別子です。翻訳しません */}
                  <h2 className="text-ink text-sm font-semibold" translate="no">
                    {asset.name}
                  </h2>
                  <span className="sp-mono text-cyan text-[0.6875rem]" translate="no">
                    {asset.licenseName}
                  </span>
                </div>
                <p className="text-ink-dim mt-1.5 text-xs leading-relaxed">
                  {ja ? asset.usage.ja : asset.usage.en}
                </p>
                <dl className="mt-3 space-y-1 text-[0.6875rem]">
                  <Row label={ja ? "著作権表示" : "Copyright"}>
                    <span translate="no">{asset.copyrightNotice}</span>
                  </Row>
                  <Row label={ja ? "配布元" : "Source"}>
                    <a
                      href={asset.sourceUrl}
                      target="_blank"
                      rel="nofollow noopener noreferrer"
                      className="hover:text-cyan break-all underline decoration-dotted underline-offset-2"
                    >
                      {asset.sourceUrl}
                    </a>
                  </Row>
                  <Row label={labels.license}>
                    <a
                      href={asset.licenseUrl}
                      target="_blank"
                      rel="nofollow noopener noreferrer"
                      className="hover:text-cyan break-all underline decoration-dotted underline-offset-2"
                    >
                      {asset.licenseUrl}
                    </a>
                  </Row>
                  {asset.modification ? (
                    <Row label={labels.modified}>
                      {ja ? asset.modification.ja : asset.modification.en}
                    </Row>
                  ) : null}
                </dl>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <section aria-labelledby="ic-commons" className="mb-12">
        <SectionHeading
          id="ic-commons"
          eyebrow="WIKIMEDIA COMMONS"
          title={ja ? "Wikimedia Commons の画像" : "Images from Wikimedia Commons"}
        />

        {published.length === 0 ? (
          /*
            画像が0件でも、それらしい一覧を作りません。
            ライセンス確認が済んでいない画像を「掲載中」に見せないためです。
          */
          <div className="sp-solid text-ink-soft p-5 text-sm leading-relaxed">
            <p>
              {ja
                ? "現在、ライセンスを確認できた Wikimedia Commons の画像はありません。"
                : "No Wikimedia Commons images have completed licence verification yet."}
            </p>
            <p className="text-ink-dim mt-2 text-xs">
              {ja
                ? "確認が済むまで、各ページは画像を使わない装飾表現で表示しています。"
                : "Until they do, pages use image-free decorative visuals."}
            </p>
          </div>
        ) : (
          <ul className="space-y-3">
            {published.map((asset) => {
              const license = getLicense(asset.licenseCode);
              const localization = getLocalization(asset.id, locale);
              const usages = getPagesUsingAsset(asset.id);

              return (
                <li key={asset.id} className="sp-solid p-4">
                  <div className="flex flex-wrap items-center gap-2">
                    <ImageLicenseBadge code={asset.licenseCode} />
                    <span className="text-ink-faint text-[0.6875rem]">
                      {labels.commercialUse}:{" "}
                      {license.commercialUseAllowed ? labels.allowed : labels.notAllowed}
                    </span>
                    <span className="text-ink-faint text-[0.6875rem]">
                      {labels.derivativeWorks}:{" "}
                      {license.derivativeWorksAllowed ? labels.allowed : labels.notAllowed}
                    </span>
                    <span className="text-ink-faint text-[0.6875rem]">
                      {labels.shareAlike}:{" "}
                      {license.shareAlikeRequired ? labels.required : labels.notRequired}
                    </span>
                  </div>

                  {/* ファイル名は識別子です。翻訳しません */}
                  <h2 className="text-ink mt-2 text-sm font-semibold" translate="no">
                    {asset.fileName}
                  </h2>
                  {localization?.caption ? (
                    <p className="text-ink-dim mt-1 text-xs leading-relaxed">
                      {localization.caption}
                    </p>
                  ) : null}

                  <dl className="mt-3 grid gap-x-4 gap-y-1 text-[0.6875rem] sm:grid-cols-2">
                    <Row label={labels.author}>
                      {asset.authorName ? (
                        asset.authorUrl ? (
                          <a
                            href={asset.authorUrl}
                            target="_blank"
                            rel="nofollow noopener noreferrer"
                            translate="no"
                            className="hover:text-cyan underline decoration-dotted underline-offset-2"
                          >
                            {asset.authorName}
                          </a>
                        ) : (
                          <span translate="no">{asset.authorName}</span>
                        )
                      ) : (
                        labels.notProvided
                      )}
                    </Row>
                    <Row label={labels.source}>
                      <a
                        href={asset.commonsPageUrl}
                        target="_blank"
                        rel="nofollow noopener noreferrer"
                        translate="no"
                        className="hover:text-cyan underline decoration-dotted underline-offset-2"
                      >
                        Wikimedia Commons
                      </a>
                    </Row>
                    <Row label={labels.license}>
                      {asset.licenseUrl ? (
                        <a
                          href={asset.licenseUrl}
                          target="_blank"
                          rel="nofollow noopener noreferrer"
                          translate="no"
                          className="hover:text-cyan underline decoration-dotted underline-offset-2"
                        >
                          {license.name}
                        </a>
                      ) : (
                        <span translate="no">{license.name}</span>
                      )}
                      {asset.isModified ? ` ${labels.modified}` : ""}
                    </Row>
                    {usages.length > 0 ? (
                      <Row label={ja ? "使用ページ" : "Used on"}>
                        <span translate="no">
                          {usages.map((usage) => usage.pageKey).join(", ")}
                        </span>
                      </Row>
                    ) : null}
                  </dl>
                </li>
              );
            })}
          </ul>
        )}
      </section>

      <section aria-labelledby="ic-policy" className="mb-4">
        <SectionHeading
          id="ic-policy"
          eyebrow="POLICY"
          title={ja ? "画像の掲載方針" : "How we handle images"}
        />
        <ul className="sp-solid divide-edge divide-y">
          {[
            ja
              ? "対象は Wikimedia Commons に登録されたファイルです。Wikipedia の記事に表示されているという理由だけで転載することはしません。"
              : "We only use files hosted on Wikimedia Commons. Appearing in a Wikipedia article is never on its own a reason to reuse an image.",
            ja
              ? "ライセンス・作者・出典を機械的に確認できない画像は掲載しません。取得できたことと、掲載してよいことは別に判定しています。"
              : "Images whose licence, author or source cannot be verified are not published. Successful retrieval and permission to publish are judged separately.",
            ja
              ? "商用利用不可（CC BY-NC など）・改変不可（CC BY-ND）・ライセンス不明の画像は使用しません。"
              : "We do not use non-commercial, no-derivatives or unknown-licence images.",
            ja
              ? "存命人物・商標・建築著作物・美術作品が写る画像は、ライセンスが自由でも自動公開しません。"
              : "Images showing living people, trademarks, architecture or artworks are never auto-published, however free the licence.",
            labels.disclaimer,
            ja
              ? "当サイトは Wikimedia Foundation とは関係がなく、同財団による推奨も受けていません。"
              : "This site is not affiliated with, nor endorsed by, the Wikimedia Foundation.",
          ].map((item) => (
            <li key={item} className="text-ink-soft px-4 py-3 text-sm leading-relaxed">
              {item}
            </li>
          ))}
        </ul>
      </section>

      <p className="text-ink-faint text-[0.6875rem]">
        <Link href={href(locale, "/legal/copyright")} className="hover:text-cyan">
          {dict.footerCopyright}
        </Link>
      </p>

      <JsonLd data={[breadcrumbJsonLd(locale, trail)]} />
    </>
  );
}

function Row({ label, children }: { label: string; children: React.ReactNode }) {
  return (
    <div className="flex gap-2">
      <dt className="text-ink-faint w-24 shrink-0">{label}</dt>
      <dd className="text-ink-soft m-0 min-w-0 flex-1 break-words">{children}</dd>
    </div>
  );
}
