import type { Metadata } from "next";
import Link from "next/link";

import { findLocale, localeCodes } from "@/sports/i18n";
import { resolveLocale } from "@/sports/lib/page";
import { sportsMetadata } from "@/sports/lib/seo";
import { href } from "@/sports/lib/url";
import { Breadcrumbs, JsonLd, SectionHeading } from "@/sports/components/ui/primitives";
import { breadcrumbJsonLd } from "@/sports/lib/structured-data";

import { wikimediaAssets, usagesForAsset } from "@/wikimedia/data/assets";
import { thirdPartyAssets } from "@/wikimedia/data/third-party";
import { ImageAttribution } from "@/wikimedia/components/ImageAttribution";
import { evaluateAsset } from "@/wikimedia/licenses";
import { CreditsFilter } from "@/wikimedia/components/CreditsFilter";
import { ImageLicenseBadge } from "@/wikimedia/components/ImageLicenseBadge";

export function generateStaticParams() {
  return localeCodes.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: {
  params: Promise<{ locale: string }>;
}): Promise<Metadata> {
  const { locale } = await params;
  const info = findLocale(locale);
  if (!info) return {};
  return sportsMetadata({
    locale: info.code,
    path: "/image-credits",
    title: info.code === "ja" ? "画像出典・ライセンス一覧" : "Image credits and licences",
    description:
      info.code === "ja"
        ? "当サイトで使用している画像の作者・出典・ライセンス・取得日の一覧です。"
        : "Every image used on this site, with its author, source, licence and retrieval date.",
  });
}

export default async function ImageCreditsPage({
  params,
}: {
  params: Promise<{ locale: string }>;
}) {
  const { locale, dict, t } = await resolveLocale(params);
  void dict;

  const published = wikimediaAssets.filter((asset) => evaluateAsset(asset).allowed);
  const pending = wikimediaAssets.filter((asset) => !evaluateAsset(asset).allowed);

  const title = locale === "ja" ? "画像出典・ライセンス一覧" : "Image credits and licences";
  const trail = [
    { label: "HOME", path: "/" },
    { label: title, path: "/image-credits" },
  ];

  return (
    <>
      <Breadcrumbs locale={locale} trail={trail} />

      <header className="mb-10">
        <p className="sp-eyebrow mb-2">IMAGE CREDITS</p>
        <h1 className="text-ink text-3xl font-extrabold sm:text-4xl">{title}</h1>
        <p className="text-ink-dim mt-3 max-w-3xl text-sm leading-relaxed">
          {locale === "ja"
            ? "当サイトで使用しているすべての画像について、作者・出典・ライセンス・取得日を記載しています。作者名・作品名・ライセンス正式名称は、どの言語のページでも原文のまま表示しています。"
            : "Author, source, licence and retrieval date for every image on this site. Author names, titles and licence names are shown in their original form in every language."}
        </p>
      </header>

      {/* 自サイトで生成した素材と、第三者素材を分けて示します */}
      <section aria-labelledby="ic-own" className="mb-12">
        <SectionHeading
          id="ic-own"
          eyebrow="OWN WORK"
          title={locale === "ja" ? "当サイトが作成した素材" : "Created by this site"}
        />
        <div className="sp-solid text-ink-soft p-5 text-sm leading-relaxed">
          {locale === "ja" ? (
            <>
              <p>
                チームエンブレム・選手のシルエット・カードの背景・OGP画像は、すべて当サイトが
                プログラムで生成したものです。第三者の著作物は含まれていません。
              </p>
              <p className="mt-2">
                チームロゴ・リーグロゴ・選手写真は、権利処理が済むまで掲載していません （
                <Link href={href(locale, "/legal/copyright")} className="text-cyan hover:underline">
                  著作権・画像利用方針
                </Link>
                ）。
              </p>
            </>
          ) : (
            <>
              <p>
                Team crests, player silhouettes, card backgrounds and OG images are generated by
                this site in code. They contain no third-party work.
              </p>
              <p className="mt-2">
                Club and league logos and player photographs are not published until the rights are
                cleared.
              </p>
            </>
          )}
        </div>
      </section>

      {thirdPartyAssets.length > 0 ? (
        <section aria-labelledby="ic-third" className="mb-12">
          <SectionHeading
            id="ic-third"
            eyebrow="THIRD PARTY"
            title={locale === "ja" ? "第三者素材" : "Third-party assets"}
            description={
              locale === "ja"
                ? "Wikimedia Commons 以外の、ライセンスに基づいて利用している素材です。"
                : "Assets used under licence from sources other than Wikimedia Commons."
            }
          />
          <ul className="space-y-3">
            {thirdPartyAssets.map((asset) => (
              <li key={asset.id} className="sp-solid p-4">
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <h3 className="text-ink text-sm font-semibold" translate="no">
                    {asset.name}
                  </h3>
                  <span className="sp-mono text-cyan text-[0.6875rem]" translate="no">
                    {asset.licenseName}
                  </span>
                </div>
                <p className="text-ink-dim mt-1.5 text-xs leading-relaxed">{t(asset.usage)}</p>
                <dl className="mt-3 space-y-1 text-[0.6875rem]">
                  <div className="flex gap-2">
                    <dt className="text-ink-faint w-24 shrink-0">
                      {locale === "ja" ? "著作権表示" : "Copyright"}
                    </dt>
                    <dd className="text-ink-soft min-w-0 flex-1" translate="no">
                      {asset.copyrightNotice}
                    </dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="text-ink-faint w-24 shrink-0">
                      {locale === "ja" ? "配布元" : "Source"}
                    </dt>
                    <dd className="min-w-0 flex-1">
                      <a
                        href={asset.sourceUrl}
                        target="_blank"
                        rel="noopener noreferrer nofollow"
                        className="text-ink-soft hover:text-cyan break-all"
                      >
                        {asset.sourceUrl}
                      </a>
                    </dd>
                  </div>
                  <div className="flex gap-2">
                    <dt className="text-ink-faint w-24 shrink-0">
                      {locale === "ja" ? "ライセンス" : "Licence"}
                    </dt>
                    <dd className="min-w-0 flex-1">
                      <a
                        href={asset.licenseUrl}
                        target="_blank"
                        rel="noopener noreferrer nofollow"
                        className="text-ink-soft hover:text-cyan break-all"
                      >
                        {asset.licenseUrl}
                      </a>
                    </dd>
                  </div>
                </dl>
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <section aria-labelledby="ic-commons" className="mb-12">
        <SectionHeading
          id="ic-commons"
          eyebrow="WIKIMEDIA COMMONS"
          title={locale === "ja" ? "Wikimedia Commons の画像" : "Images from Wikimedia Commons"}
        />

        {published.length === 0 ? (
          <div className="sp-solid text-ink-soft p-5 text-sm leading-relaxed">
            <p>
              {locale === "ja"
                ? "現在、Wikimedia Commons の画像は掲載していません。"
                : "No Wikimedia Commons images are currently published."}
            </p>
            <p className="text-ink-dim mt-2 text-xs">
              {locale === "ja"
                ? "画像取得パイプラインは実装済みですが、ライセンス・作者・出典が確認できた画像だけを掲載する方針のため、確認が完了するまでは生成ビジュアルを表示しています。"
                : "The retrieval pipeline is implemented, but we only publish images whose licence, author and source we have verified. Until then, generated visuals are used."}
            </p>
            {pending.length > 0 ? (
              <p className="text-caution mt-2 text-xs">
                {locale === "ja"
                  ? `確認待ちの候補：${pending.length} 件`
                  : `Candidates awaiting review: ${pending.length}`}
              </p>
            ) : null}
          </div>
        ) : (
          <CreditsFilter locale={locale}>
            {published.map((asset) => (
              <li
                key={asset.id}
                className="sp-solid p-4"
                data-license={asset.licenseCode}
                data-author={asset.authorName ?? ""}
                data-title={asset.title}
                data-pages={usagesForAsset(asset.id)
                  .map((usage) => usage.path)
                  .join(" ")}
              >
                <div className="flex flex-wrap items-baseline justify-between gap-2">
                  <h3 className="text-ink text-sm font-semibold" translate="no">
                    {asset.title}
                  </h3>
                  <ImageLicenseBadge code={asset.licenseCode} />
                </div>
                <ImageAttribution asset={asset} locale={locale} variant="full" className="mt-3" />
                <p className="text-ink-faint mt-2 text-[0.625rem]">
                  {locale === "ja" ? "掲載ページ" : "Used on"}:{" "}
                  {usagesForAsset(asset.id).map((usage) => (
                    <Link
                      key={`${usage.path}-${usage.slot}`}
                      href={href(locale, usage.path)}
                      className="hover:text-cyan mr-2 underline decoration-dotted underline-offset-2"
                    >
                      {usage.path}
                    </Link>
                  ))}
                </p>
              </li>
            ))}
          </CreditsFilter>
        )}
      </section>

      <section aria-labelledby="ic-policy" className="mb-4">
        <SectionHeading
          id="ic-policy"
          eyebrow="POLICY"
          title={locale === "ja" ? "画像の掲載方針" : "How we choose images"}
        />
        <ul className="sp-solid divide-edge divide-y">
          {(locale === "ja"
            ? [
                "Wikimedia Commons のファイルページでライセンス・作者・出典を確認できた画像のみを掲載します",
                "Wikipedia の記事に載っているという理由だけで転載しません",
                "商用利用不可（CC BY-NC など）・改変不可（CC BY-ND）・ライセンス不明の画像は使用しません",
                "パブリックドメインと CC0 以外は、人間が内容を確認してから公開します",
                "存命人物・商標・建築著作物・美術作品が写る画像は、ライセンスが自由でも自動公開しません",
                "適切な画像が無いときは、無理に画像を使わず生成ビジュアルを表示します",
              ]
            : [
                "We publish only images whose licence, author and source we could verify on the Commons file page",
                "We never copy an image just because it appears in a Wikipedia article",
                "We do not use non-commercial (CC BY-NC), no-derivatives (CC BY-ND) or unknown-licence images",
                "Anything other than public domain and CC0 is reviewed by a person before publication",
                "Images showing living people, trademarks, architecture or artworks are never auto-published",
                "When no suitable image exists we show a generated visual instead of forcing one",
              ]
          ).map((item) => (
            <li key={item} className="text-ink-soft px-4 py-3 text-sm">
              {item}
            </li>
          ))}
        </ul>
        <p className="text-ink-faint mt-3 text-[0.6875rem]">
          {locale === "ja"
            ? "当サイトは Wikimedia Foundation とは無関係であり、公認を受けたものではありません。"
            : "This site is not affiliated with or endorsed by the Wikimedia Foundation."}
        </p>
      </section>

      <JsonLd data={[breadcrumbJsonLd(locale, trail)]} />
    </>
  );
}
