/**
 * Demo fixtures.
 *
 * EVERY NAME, ADDRESS, PHONE NUMBER AND EMAIL IN THIS FILE IS FICTIONAL.
 * No real salon, staff member or customer is represented. Contact details use
 * the reserved `.invalid` TLD and the 090-0000-xxxx range so nothing here can
 * reach a real person.
 */

export const DEMO_ORGANIZATION = {
  name: "デモビューティーグループ",
  nameKana: "デモビューティーグループ",
  slug: "demo-beauty-group",
  timezone: "Asia/Tokyo",
  billingEmail: "billing@demo.example.invalid",
} as const;

export const DEMO_STORES = [
  {
    slug: "demo-beauty-salon-a",
    name: "Demo Beauty Salon 一号店",
    nameKana: "デモビューティーサロンイチゴウテン",
    industry: "hair",
    phone: "03-0000-0001",
    email: "store-a@demo.example.invalid",
    postalCode: "100-0000",
    prefecture: "架空県",
    city: "架空市",
    addressLine: "デモ町1-1-1 デモビル2F",
    accessNote: "架空駅 徒歩1分（デモデータ）",
    description: "デモ用の架空店舗です。実在の店舗ではありません。",
    approvalMode: "instant",
    slotIntervalMinutes: 15,
    bookingCutoffMinutes: 120,
    maxAdvanceDays: 60,
    bufferMinutes: 5,
    cancelDeadlineHours: 24,
  },
  {
    slug: "demo-beauty-salon-b",
    name: "Demo Beauty Salon 二号店",
    nameKana: "デモビューティーサロンニゴウテン",
    industry: "nail",
    phone: "03-0000-0002",
    email: "store-b@demo.example.invalid",
    postalCode: "100-0001",
    prefecture: "架空県",
    city: "架空市",
    addressLine: "デモ町2-2-2 デモアネックス3F",
    accessNote: "架空駅 徒歩3分（デモデータ）",
    description: "デモ用の架空店舗です。実在の店舗ではありません。",
    approvalMode: "request",
    slotIntervalMinutes: 30,
    bookingCutoffMinutes: 180,
    maxAdvanceDays: 45,
    bufferMinutes: 10,
    cancelDeadlineHours: 48,
  },
] as const;

export const DEMO_STAFF = [
  {
    code: "S001",
    name: "架空 一花",
    nameKana: "カクウ イチカ",
    displayName: "ICHIKA",
    title: "店長 / スタイリスト",
    bio: "デモデータ用の架空スタッフです。",
    employmentType: "full_time",
    designationFee: 1100,
    storeIndex: 0,
    durationFactorBps: 10_000,
  },
  {
    code: "S002",
    name: "架空 二郎",
    nameKana: "カクウ ジロウ",
    displayName: "JIRO",
    title: "トップスタイリスト",
    bio: "デモデータ用の架空スタッフです。",
    employmentType: "full_time",
    designationFee: 1650,
    storeIndex: 0,
    durationFactorBps: 9_000,
  },
  {
    code: "S003",
    name: "架空 三奈",
    nameKana: "カクウ ミナ",
    displayName: "MINA",
    title: "スタイリスト",
    bio: "デモデータ用の架空スタッフです。",
    employmentType: "part_time",
    designationFee: 550,
    storeIndex: 0,
    durationFactorBps: 11_000,
  },
  {
    code: "S004",
    name: "架空 四季",
    nameKana: "カクウ シキ",
    displayName: "SHIKI",
    title: "アシスタント",
    bio: "デモデータ用の架空スタッフです。",
    employmentType: "trainee",
    designationFee: 0,
    storeIndex: 0,
    durationFactorBps: 12_500,
  },
  {
    code: "S005",
    name: "架空 五月",
    nameKana: "カクウ サツキ",
    displayName: "SATSUKI",
    title: "店長 / ネイリスト",
    bio: "デモデータ用の架空スタッフです。",
    employmentType: "full_time",
    designationFee: 1100,
    storeIndex: 1,
    durationFactorBps: 10_000,
  },
  {
    code: "S006",
    name: "架空 六花",
    nameKana: "カクウ リッカ",
    displayName: "RIKKA",
    title: "ネイリスト（業務委託）",
    bio: "デモデータ用の架空スタッフです。",
    employmentType: "freelance",
    designationFee: 880,
    storeIndex: 1,
    durationFactorBps: 10_000,
  },
] as const;

export const DEMO_RESOURCE_TYPES = [
  { key: "chair", name: "セット面", kind: "chair" },
  { key: "shampoo", name: "シャンプー台", kind: "shampoo_stand" },
  { key: "nail_table", name: "ネイルテーブル", kind: "nail_table" },
  { key: "bed", name: "施術ベッド", kind: "bed" },
  { key: "private_room", name: "個室", kind: "private_room" },
] as const;

export const DEMO_SERVICE_CATEGORIES = [
  "カット",
  "カラー",
  "パーマ・ストレート",
  "トリートメント・ヘッドスパ",
  "ネイル",
  "アイラッシュ",
  "フェイシャル・ボディ",
] as const;

/**
 * 20 menu items across the two demo stores.
 *
 * The colour and perm entries carry an unattended window so the demo shows the
 * "stylist is free while the colour processes" behaviour that the occupancy
 * engine exists for.
 */
export const DEMO_SERVICES = [
  {
    name: "カット",
    category: "カット",
    price: 5500,
    duration: 60,
    prep: 0,
    cleanup: 5,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "カット＋シャンプーブロー",
    category: "カット",
    price: 7150,
    duration: 75,
    prep: 0,
    cleanup: 5,
    resources: ["chair", "shampoo"],
    storeIndex: 0,
  },
  {
    name: "前髪カット",
    category: "カット",
    price: 1650,
    duration: 20,
    prep: 0,
    cleanup: 0,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "メンズカット",
    category: "カット",
    price: 4400,
    duration: 45,
    prep: 0,
    cleanup: 5,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "リタッチカラー",
    category: "カラー",
    price: 6600,
    duration: 90,
    prep: 5,
    cleanup: 10,
    unattendedStart: 30,
    unattended: 30,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "フルカラー",
    category: "カラー",
    price: 8800,
    duration: 120,
    prep: 5,
    cleanup: 10,
    unattendedStart: 40,
    unattended: 40,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "ハイライトカラー",
    category: "カラー",
    price: 13200,
    duration: 150,
    prep: 10,
    cleanup: 10,
    unattendedStart: 60,
    unattended: 40,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "デジタルパーマ",
    category: "パーマ・ストレート",
    price: 14300,
    duration: 150,
    prep: 10,
    cleanup: 10,
    unattendedStart: 50,
    unattended: 40,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "縮毛矯正",
    category: "パーマ・ストレート",
    price: 18700,
    duration: 180,
    prep: 10,
    cleanup: 15,
    unattendedStart: 60,
    unattended: 30,
    resources: ["chair"],
    storeIndex: 0,
  },
  {
    name: "ヘッドスパ 30分",
    category: "トリートメント・ヘッドスパ",
    price: 4400,
    duration: 30,
    prep: 0,
    cleanup: 5,
    resources: ["shampoo"],
    storeIndex: 0,
  },
  {
    name: "システムトリートメント",
    category: "トリートメント・ヘッドスパ",
    price: 5500,
    duration: 45,
    prep: 0,
    cleanup: 5,
    resources: ["shampoo"],
    storeIndex: 0,
  },
  {
    name: "炭酸スパ",
    category: "トリートメント・ヘッドスパ",
    price: 3300,
    duration: 20,
    prep: 0,
    cleanup: 5,
    resources: ["shampoo"],
    storeIndex: 0,
  },
  {
    name: "ジェルネイル ワンカラー",
    category: "ネイル",
    price: 6600,
    duration: 90,
    prep: 5,
    cleanup: 10,
    resources: ["nail_table"],
    storeIndex: 1,
  },
  {
    name: "ジェルネイル デザイン",
    category: "ネイル",
    price: 9900,
    duration: 120,
    prep: 5,
    cleanup: 10,
    resources: ["nail_table"],
    storeIndex: 1,
  },
  {
    name: "フィルイン",
    category: "ネイル",
    price: 7700,
    duration: 100,
    prep: 5,
    cleanup: 10,
    resources: ["nail_table"],
    storeIndex: 1,
  },
  {
    name: "ジェルオフのみ",
    category: "ネイル",
    price: 3300,
    duration: 40,
    prep: 0,
    cleanup: 5,
    resources: ["nail_table"],
    storeIndex: 1,
  },
  {
    name: "フットネイル",
    category: "ネイル",
    price: 8800,
    duration: 110,
    prep: 5,
    cleanup: 10,
    resources: ["nail_table"],
    storeIndex: 1,
  },
  {
    name: "まつげエクステ 100本",
    category: "アイラッシュ",
    price: 7700,
    duration: 90,
    prep: 5,
    cleanup: 10,
    resources: ["bed"],
    storeIndex: 1,
  },
  {
    name: "まつげパーマ",
    category: "アイラッシュ",
    price: 6600,
    duration: 75,
    prep: 5,
    cleanup: 10,
    resources: ["bed"],
    storeIndex: 1,
  },
  {
    name: "フェイシャルトリートメント 60分",
    category: "フェイシャル・ボディ",
    price: 11000,
    duration: 60,
    prep: 5,
    cleanup: 10,
    resources: ["private_room"],
    storeIndex: 1,
  },
] as const;

export const DEMO_PRODUCTS = [
  { sku: "P-001", name: "デモシャンプー 300ml", purchase: 1200, selling: 3300 },
  { sku: "P-002", name: "デモトリートメント 250g", purchase: 1400, selling: 3850 },
  { sku: "P-003", name: "デモヘアオイル 100ml", purchase: 1100, selling: 3080 },
  { sku: "P-004", name: "デモスタイリングバーム 45g", purchase: 900, selling: 2640 },
  { sku: "P-005", name: "デモヘアミルク 120ml", purchase: 950, selling: 2750 },
  { sku: "P-006", name: "デモキューティクルオイル 15ml", purchase: 600, selling: 1980 },
  { sku: "P-007", name: "デモネイルファイル", purchase: 200, selling: 660 },
  { sku: "P-008", name: "デモまつげ美容液 5ml", purchase: 1300, selling: 3960 },
  { sku: "P-009", name: "デモクレンジングジェル 150ml", purchase: 1000, selling: 2970 },
  { sku: "P-010", name: "デモ保湿クリーム 50g", purchase: 1500, selling: 4400 },
] as const;

/** Fictional surnames and given names used to compose 50 demo customers. */
export const DEMO_SURNAMES = [
  ["架空", "カクウ"],
  ["仮野", "カリノ"],
  ["見本", "ミホン"],
  ["試作", "シサク"],
  ["標本", "ヒョウホン"],
  ["例田", "レイダ"],
  ["模擬", "モギ"],
  ["架設", "カセツ"],
  ["仮設", "カセツ"],
  ["想定", "ソウテイ"],
] as const;

export const DEMO_GIVEN_NAMES = [
  ["あかり", "アカリ", "female"],
  ["いつき", "イツキ", "other"],
  ["うらら", "ウララ", "female"],
  ["えいた", "エイタ", "male"],
  ["おとは", "オトハ", "female"],
  ["かなた", "カナタ", "male"],
  ["きらり", "キラリ", "female"],
  ["くるみ", "クルミ", "female"],
  ["けんと", "ケント", "male"],
  ["こはる", "コハル", "female"],
] as const;

export const DEMO_TAGS = [
  { name: "VIP", color: "#b45309" },
  { name: "新規", color: "#0369a1" },
  { name: "要フォロー", color: "#be123c" },
  { name: "アレルギー確認済", color: "#15803d" },
  { name: "SNS経由", color: "#7c3aed" },
] as const;

export const DEMO_ACQUISITION_SOURCES = [
  "紹介",
  "看板",
  "SNS",
  "検索",
  "通りがかり",
  "チラシ",
] as const;

/**
 * Chart templates.
 *
 * The industry-specific fields the spec asks for live here as data rows, not
 * as database columns, so a salon can add "使用ジェルブランド" without a
 * migration.
 */
export const DEMO_RECORD_TEMPLATES = [
  {
    key: "hair",
    industry: "hair",
    name: "ヘア用カルテ",
    storeIndex: 0,
    isDefault: true,
    fields: [
      {
        key: "hair_type",
        label: "髪質",
        type: "select",
        section: "診断",
        options: ["軟毛", "普通", "硬毛"],
      },
      {
        key: "damage_level",
        label: "ダメージレベル",
        type: "select",
        section: "診断",
        options: ["なし", "軽度", "中度", "重度"],
      },
      { key: "color_formula", label: "カラー配合", type: "color_formula", section: "薬剤" },
      { key: "chemical", label: "使用薬剤", type: "text", section: "薬剤" },
      { key: "processing_minutes", label: "放置時間（分）", type: "number", section: "薬剤" },
      { key: "cut_detail", label: "カット内容", type: "textarea", section: "施術" },
      { key: "perm_history", label: "パーマ履歴", type: "textarea", section: "履歴" },
      {
        key: "finish_photo",
        label: "仕上がり写真",
        type: "photo",
        section: "写真",
        sensitive: true,
      },
    ],
  },
  {
    key: "nail",
    industry: "nail",
    name: "ネイル用カルテ",
    storeIndex: 1,
    isDefault: true,
    fields: [
      {
        key: "nail_condition",
        label: "爪の状態",
        type: "select",
        section: "診断",
        options: ["良好", "乾燥", "二枚爪", "深爪"],
      },
      {
        key: "nail_length",
        label: "長さ",
        type: "select",
        section: "診断",
        options: ["ショート", "ミディアム", "ロング"],
      },
      {
        key: "nail_shape",
        label: "形",
        type: "select",
        section: "診断",
        options: ["ラウンド", "スクエア", "オーバル", "アーモンド"],
      },
      { key: "colors_used", label: "使用カラー", type: "text", section: "施術" },
      { key: "gel_used", label: "使用ジェル", type: "text", section: "施術" },
      { key: "parts_used", label: "使用パーツ", type: "text", section: "施術" },
      { key: "fill_in_history", label: "フィルイン履歴", type: "textarea", section: "履歴" },
      {
        key: "off_method",
        label: "オフ方法",
        type: "select",
        section: "履歴",
        options: ["マシンオフ", "ソークオフ", "フィルイン"],
      },
      { key: "allergy_checked", label: "アレルギー確認", type: "checkbox", section: "確認" },
      {
        key: "photo_left",
        label: "左手デザイン写真",
        type: "photo",
        section: "写真",
        sensitive: true,
      },
      {
        key: "photo_right",
        label: "右手デザイン写真",
        type: "photo",
        section: "写真",
        sensitive: true,
      },
    ],
  },
  {
    key: "eyelash",
    industry: "eyelash",
    name: "アイラッシュ用カルテ",
    storeIndex: 1,
    isDefault: false,
    fields: [
      {
        key: "curl",
        label: "カール",
        type: "select",
        section: "仕様",
        options: ["Jカール", "Cカール", "Dカール", "SCカール"],
      },
      { key: "length", label: "長さ(mm)", type: "text", section: "仕様" },
      { key: "thickness", label: "太さ(mm)", type: "text", section: "仕様" },
      { key: "count", label: "本数", type: "number", section: "仕様" },
      { key: "glue", label: "使用グルー", type: "text", section: "薬剤" },
      { key: "allergy_checked", label: "アレルギー確認", type: "checkbox", section: "確認" },
    ],
  },
  {
    key: "esthetic",
    industry: "esthetic",
    name: "エステ用カルテ",
    storeIndex: 1,
    isDefault: false,
    fields: [
      { key: "skin_condition", label: "肌状態", type: "textarea", section: "診断" },
      {
        key: "treatment_area",
        label: "施術部位",
        type: "multi_select",
        section: "施術",
        options: ["フェイス", "デコルテ", "背中", "脚", "腕"],
      },
      { key: "cosmetics_used", label: "使用化粧品", type: "text", section: "施術" },
      { key: "contraindications", label: "禁忌事項", type: "textarea", section: "確認" },
      {
        key: "before_photo",
        label: "ビフォー写真",
        type: "photo",
        section: "写真",
        sensitive: true,
      },
      {
        key: "after_photo",
        label: "アフター写真",
        type: "photo",
        section: "写真",
        sensitive: true,
      },
    ],
  },
] as const;

/** Demo logins. Passwords are obviously non-production and documented as such. */
export const DEMO_USERS = [
  {
    email: "owner@demo.example.invalid",
    name: "デモ 法人オーナー",
    roleKey: "org_owner",
    storeIndex: null,
    staffCode: null,
  },
  {
    email: "manager@demo.example.invalid",
    name: "デモ 店長",
    roleKey: "store_manager",
    storeIndex: 0,
    staffCode: "S001",
  },
  {
    email: "reception@demo.example.invalid",
    name: "デモ 受付",
    roleKey: "receptionist",
    storeIndex: 0,
    staffCode: null,
  },
  {
    email: "stylist@demo.example.invalid",
    name: "デモ スタイリスト",
    roleKey: "staff",
    storeIndex: 0,
    staffCode: "S002",
  },
  {
    email: "viewer@demo.example.invalid",
    name: "デモ 閲覧専用",
    roleKey: "viewer",
    storeIndex: 0,
    staffCode: null,
  },
] as const;
